name: pr_check

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    paths-ignore:
      - 'static/**'
      - '**.md'
      - '.gitignore'
      - '.github/ISSUE_TEMPLATE/**'
  workflow_dispatch:

jobs:
  analyze:
    name: Dart Analyze
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: "3.44.9"
          cache: true

      - name: Get Flutter dependencies
        run: flutter pub get
        env:
          GIT_LFS_SKIP_SMUDGE: 1

      - name: Dart Analyze
        run: dart analyze --no-fatal-warnings
